### ISSUE TITLE
Sync crash in the field 1

### ISSUE THREAD

**Issue by jencastrodoesstuff** [digidem/mapeo-mobile#334]
Using apk v.2.0.0 beta 5
Custom configurations temporarily deactivated (observations captured with no-key configurations syncing with the device that had key secured configurations required temporary renaming of installed default folder to "default-null")

m2m sync attempt in Setapo MDD Peru
![20200304_070513](https://user-images.githubusercontent.com/33264095/76228543-40312380-61f7-11ea-9a7d-75f3cf844f10.jpg)
reattempt  resulted in crash
![20200304_070545](https://user-images.githubusercontent.com/33264095/76228730-7cfd1a80-61f7-11ea-9ac1-0103e3b5c10b.jpg)

Note about this device.
![20200304_071429](https://user-images.githubusercontent.com/33264095/76229390-7e7b1280-61f8-11ea-9112-b1a318ad907a.jpg)
Device file names. the Blackview displayed file names in all caps. (may not be relevant)

**Comment by noffle** [comment]
Was the problem reproducible (as in, same error when/if you retried?). It *looks* like the connection was maybe just lost, which could be random/intermittent.

**Comment by jencastrodoesstuff** [comment]
This was not me. It was our partners in the field with David (ISS). I only
transmit relevant details of what he reported to me. Also they have a
practice of trying again because they have been part of trial and error
processes for the last 15 months. They know to check connections and try
again. But in the field I don't know what they actually did. They are
dealing with a lot on those trips.

*Jen Castro*
*(Remote from Montreal)*
*Program Coordinator - **Digital Democracy*
Tel Perú:  +51(1)7007968 , Canada: +16479455252 , WhatsApp: +17789984058,
Skype:  live:jen_5964

**Pido disculpas por cualquier error gramática u ortográfica. Estoy en el
proceso de mejorar mi nivel de castellano y aprecio su paciencia.

**Comment by gmaclennan** [comment]
Hi @jencastrodoesstuff, I can think of two possibilities that could result in this error:

1. One of the two devices is out of free space on disk
2. The network connection was broken (weak wifi etc).

@noffle has done a lot of work in the last 3 weeks to give more meaningful errors for (1) when the disk is full (see https://github.com/digidem/mapeo-core/issues/73). These fixes are not released yet, but will come in a future release. @noffle are these part of the breaking change release for end of April right?

As for (2) I have [opened an issue](https://github.com/digidem/mapeo-mobile/issues/331) to add WiFi signal strength to the sync screen, so that we can warn the user if the signal is weak (which can cause sync issues). However I don't think this is the case here.

The other option is that again this is an issue with one of the two devices being an alpha release, not beta.5. I checked through the bugsnag reporting and I do see this same error reported (`Error: write EPIPE`) reported on March 2nd at about 12pm local time, but it is reported from a device using `v2.0.0-alpha.0`. It seems like that this error was seen after March 2nd, but that this phone has not connected to the internet to report the error. However I think there is a strong chance that one of the two devices involved in this sync was running an alpha, not the beta.

**Comment by jencastrodoesstuff** [comment]
Thanks for all this work.. and for being so thorough in investigating
possibilities. I have already written Jaime, Lucho, Walter and David about
ways to confirm installed app versions and config versions with
screencaptures.

In addition, I asked David to delete the copies of alpha zero that might be
floating around the ECA office. That error is on me. At the time I did not
fully understand the alpha-beta naming conventions and also did not
understand how many and which final versions were developed while the team
was in Andoas.

Hopefully they can update the devices with issues and give sync a shot
again with success.


*Jen Castro*
*(Remote from Montreal)*
*Program Coordinator - **Digital Democracy*
Tel Perú:  +51(1)7007968 , Canada: +16479455252 , WhatsApp: +17789984058,
Skype:  live:jen_5964

**Pido disculpas por cualquier error gramática u ortográfica. Estoy en el
proceso de mejorar mi nivel de castellano y aprecio su paciencia.

**Comment by gmaclennan** [comment]
Thanks @jencastrodoesstuff I've been thinking through several improvements to the release process that should make this less confusing in the future.

**Comment by noffle** [comment]
> @noffle are these part of the breaking change release for end of April right?

yes!

**Comment by noffle** [comment]
Are there any TODOs left for this issue? If not we can close for now.

**Comment by gmaclennan** [comment]
Let's wait to hear back from partners about whether this was an issue because of disk space or alpha versions. I am speaking to them at 9am PT today.

**Comment by gmaclennan** [comment]
Confirmed that this was caused by syncing with alpha.0
