### ISSUE TITLE
Support for Android Go devices

### ISSUE THREAD

**Issue by arky** [digidem/mapeo-mobile#337]
Am starting a project in southeast asia. Looking for sub $100 devices to buy locally would be able to run mapeo-mobile without any issues. 

Considering looking at Android Go series of devices that are being sold here. Would you foresee any issues with this category of hardware.

https://www.nokia.com/phones/vi_vn/nokia-1-0#apps

https://en.wikipedia.org/wiki/Comparison_of_Android_Go_products

Alternative Android One tend to be more expensive for limited project budgets.

**Comment by arky** [comment]
Supersede bug https://github.com/digidem/mapeo-mobile/issues/294

**Comment by gmaclennan** [comment]
Thanks for this @arky, I've just been looking through the requirements, and the main limitations are:

- App is less than 40Mb on disk
- Works on <= 1Gb Ram

I just reduced our APK size to 52.4Mb by only including support for ArmV7 and Arm64 processors (removing Intel support to a separate APK), but we could create separate APKs for 32-bit arm and 64-bit Arm and looking at the APK with https://apkanalyzer.xyz I think would reduce the size to about 30Mb, but when the app loads it extracts the Node code from the APK, which could make the on-disk size larger (I haven't checked that yet).

Another way to reduce memory is to switch to the [Hermes JavaScript engine](https://hermesengine.dev) for React Native, but currently it [does not support JS Internationalization](https://github.com/facebook/hermes/issues/23) which we use for translating dates and numbers, however a workaround would be to use [`fbt`](https://github.com/facebook/fbt) but that is more work (we currently use [`react-intl`](https://github.com/formatjs/react-intl) for internationalization).

The Mapbox GL maps are the most memory and processor-heavy parts of the app I think. It might be fine on low-end devices though - would need some testing.

We can also reduce memory usage by using [`react-native-screens`](https://github.com/software-mansion/react-native-screens) for app navigation. I turned it off before because it had a bug where clicks were not registered for a second after a screen transition. This might have been fixed now.

We need to set up some kind of memory and performance profiling so we can actually test which of these measures will actually make a difference.

Here are some resources I found for preparing an app for android Go:

- https://developer.android.com/docs/quality-guidelines/build-for-billions/device-capacity#androidgo
- https://medium.com/googleplaydev/how-to-optimize-your-app-for-android-go-edition-f0d2bedf9e03
- https://stackoverflow.com/questions/48382836/android-go-app-test?rq=1

I think it would be good to continue to reduce memory use and app size in order to support these devices and make Mapeo more efficient. If you have a chance to test it I'd be interested to know the results.

**Comment by gmaclennan** [comment]
I profiled Mapeo and its memory usage starts at about 256Mb and increases to about 400Mb when navigating between screens. There is a library we can use [`react-native-screens`](https://github.com/software-mansion/react-native-screens) which reduces max memory usage to about 325Mb, but it seems to make the navigation a bit "janky". If we update our navigation library then that might improve.

**Comment by arky** [comment]
@gmaclennan Thanks for looking into this. 

If could you share the instructions for profiling mapeo-mobile app. I'll pitch in and help.

**Comment by arky** [comment]
Closing this bug as Android Go devices have been disconnected
