### ISSUE TITLE
Text cut off on category and button labels

### ISSUE THREAD

**Issue by emreiser** [digidem/mapeo-mobile#502]
**Description**
Label text is cut off in observation categories and buttons. Single word labels appear truncated and text-wrap not working for multi-word category labels. Issue appears in observation categories + buttons in observation form, empty observations list, project config screen and photo capture modal. 

<img src="https://user-images.githubusercontent.com/3493841/101398855-b48b1700-389c-11eb-98c3-8fd0953ced0c.jpg" alt="alt text" width="250px">
<img src="https://user-images.githubusercontent.com/3493841/101402001-249b9c00-38a1-11eb-9510-b6b1d513f735.jpg" alt="alt text" width="250px">
<img src="https://user-images.githubusercontent.com/3493841/101402015-2a917d00-38a1-11eb-9022-601d5147fbfb.jpg" alt="alt text" width="250px">
<img src="https://user-images.githubusercontent.com/3493841/101402024-2e250400-38a1-11eb-87de-23b0a6c3a17a.jpg" alt="alt text" width="250px">

**Device info**
Phone model: OnePlus A6013
Android: 10
Mapeo version: 5.1.0.974.974
Build: QKQ1.190716.003

**Comment by gmaclennan** [comment]
Thanks for the report @emreiser 

A quick search and this seems to be an issue with React-Native and the OnePlus devices when the font for the device is selected as "Slate" rather than Roboto. There must be a bug in the measurements for this font. See:

https://github.com/facebook/react-native/issues/15114#issuecomment-335797756
https://forums.expo.io/t/text-cut-off-on-oneplus-device/4999/9
https://github.com/facebook/react-native/issues/24544

It looks like the workaround is to explicitly set the font to be "Roboto" for the app, although I am unclear whether we also need to include a copy of the font in the app installer. I think we can only test this by running it on a OnePlus device, so when I have time I will create a test APK for you to install and check.

**Comment by emreiser** [comment]
Thanks @gmaclennan ! Glad it's likely an easy fix. Happy to test an APK whenever you have one.
