### ISSUE TITLE
(Front) Prevent each progress event from causing a re-render

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#538]
**Description :**
Debounce p2p upgrade progress events before they are sent over the bridge to React Native, to avoid too many events blocking either the IPC bridge or the UI.

Blocked by : 

**Acceptance Criteria :**
TO ADD

**Technical Notes:**
TO ADD

**Points:**
3pts

**Blocked by**
https://github.com/digidem/mapeo-mobile/issues/536

**Comment by hackergrrl** [comment]
@gmaclennan I was thinking about this, and I wonder if the rate-limiting should happen in `src/backend/lib/upgrade-{server,download}.js` instead, at the source? My reasoning is that we can avoid calling `emit()` **tons** of extra times this way (around 10,000 for a 139mb download), when we only really need 100 (1 per whole number percent). I'm just a little worried about extra CPU cost in such a tight loop.

**Comment by gmaclennan** [comment]
@noffle, I hear you. I don't think calling `emit()` in itself has a significant overhead (all streams we use are event emitters too, and are calling their own `emit()` all those times too). I guess `upgradeManager.emit()` does create a new object every time, which needs to be garbage collected, which does have an overhead. It feels a bit like premature optimization, at the expense of slightly more complicated implementation (debouncing in two places rather than one), but happy to go ahead and rate-limit `{server,download}.js` since it's not too hard to do.

**Comment by hackergrrl** [comment]
Fixed by https://github.com/digidem/mapeo-mobile/pull/588
