### ISSUE TITLE
Please add Malagasy to the language list

### ISSUE THREAD

**Issue by kusmer** [digidem/mapeo-mobile#741]
My colleagues at Health In Harmony would like to support translating Mapeo into Malagasy, the language of Madagascar.  Please add it to the list so we can use CrowdIn to do so.  

You can see the teams that will be helping translate Mapeo into Indonesian and Malagasy at https://healthinharmony.org/team/.

Thank you! 

Steve Kusmer
Health In Harmony

**Comment by ErikSin** [comment]
@kusmer thanks for bringing this up! I will talk to the rest of the tech team early next week and will let you know our next steps forward!

**Comment by kusmer** [comment]
Thank you, @ErikSin! We'll be starting on Indonesian in the next week or two on CrowdIn.

**Comment by gmaclennan** [comment]
Hi @kusmer I have added Malagasy to the list of languages that can be translated in Crowdin, so you should be able to start adding translations there. We currently do not have very robust logic for what is included in the app: currently any language that has at least one word translated will be shown as a language choice in the settings screen (https://github.com/digidem/mapeo-mobile/blob/develop/src/frontend/context/IntlContext.js#L33-L41), as long as it is listed in the [languages.json](https://github.com/digidem/mapeo-mobile/blob/develop/src/frontend/languages.json) file (this file is used for showing English and native language names for each language).

Crowdin has an option to only include translations that have been proof-read, but right now we do not use that setting. When you add translations to Crowdin, it will automatically create a Pull Request to this repo, and once that is merged then the next release of Mapeo will include those translations.

Please note also that the names of the categories that are shown when you create a new observation are currently in a separate translations project: https://crowdin.com/project/mapeo-defaut-config This is separate because we support adding a custom config with custom categories (we aim to improve the UX and documentation for this in the future).

We do want to merge the different Crowdin projects into a single project in the future, to make it easier for translators. This requires updating our translation scripts and Github integrations for Crowdin. We also want to consider criteria for when a language is shown as an option for the app, e.g. should it be shown as an option if only one word is translated? Or should we have a minimum translation percentage before we show it as an option? Your feedback and suggestions on this would be most welcome.
