### ISSUE TITLE
Map View / Bg Map Manager

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-mobile#939]
**Description**
User clicked on the map button to open available maps, horizontal scroll

**Screens**
Background Maps
Manage Maps
Close

**Copydeck**
https://docs.google.com/spreadsheets/d/1Eco_G5hmAqnWW5NfzpAeeMgn8L5c61VO_PnkU7mSIRI/edit#gid=116684765

**Design**
https://www.figma.com/file/sxz2NvysPVab6ZTqs6f57K/Cobra-Collective?node-id=293%3A3004
Note from Sabella:
Dev might want to adjust the size of the thumbnails so the user sees a preview of the row and knows to scroll horizontally (we've talked about this in the past in other concepts with horizontal scrolling). This shows what I mean, one item is clipped to the right as an indicator that there is more to the right https://miro.medium.com/max/1400/1*2T03m1plHOiftBPo4UT0fg.png

**Comment by ErikSin** [comment]
couple of small things here based on the designs. okay to do as follow ups:

- missing: name of map under each thumbnail
- missing: border to highlight currently selected map
- missing: description of currently selected map with info about offline areas. fine to skip this one since we're not dealing with offline areas for first iteration
- too much space between close button and bottom of screen

**Comment by ErikSin** [comment]
[container spans the entire width of the sheet, causing presses outside of what may be a reasonable area from the intended target text to be registered. adjusting the width and/or hitslop of this touchable would help](https://github.com/digidem/mapeo-mobile/pull/966#discussion_r879876358)
